public with sharing class Rocket_GlobalConstants {
    public static final String ROCKET_COMMUNITY_NAME = 'Rocket';

    // Managed Content
    public static final String NODE_IMAGE_ALT_TEXT = 'altText';
    public static final String NODE_IMAGE_SOURCE = 'source';
    public static final String NODE_IMAGE_THUMB_URL = 'thumbUrl';
    public static final String NODE_IMAGE_TITLE = 'title';

    // Logging
    public static final String ERROR = 'ERROR';
    public static final String WARN = 'WARN';
    public static final String INFO = 'INFO';
    public static final String DEBUG = 'DEBUG';

}